name: Close stale PRs

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 0
          days-before-close: 1
          stale-pr-message: "This PR has been marked as stale due to inactivity. It will be closed if no further activity occurs."
          close-pr-message: "Closing this PR due to inactivity."
          only-pr-labels: ""       # optional: only PRs with some labels
          exempt-pr-labels: "do-not-close"
          operations-per-run: 200
